# Generated by Django 4.0.2 on 2022-10-01 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_color_size_product_product_code_product_color_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='Color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Size',
        ),
    ]
