# Generated by Django 4.0.3 on 2022-10-02 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delivery_charge_order_shippingaddress_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='delivery_charge',
            name='w_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
