# Generated by Django 4.0.3 on 2022-10-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_delivery_charge_w_delivery'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupon_code', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.FloatField(blank=True, default=0, null=True)),
            ],
        ),
    ]
