# Generated by Django 4.0.3 on 2022-10-02 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cupon_code',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
