# Generated by Django 4.0.3 on 2022-10-02 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_cupon_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cupon_code',
            field=models.CharField(blank=True, default='None', max_length=200, null=True),
        ),
    ]
