# Generated by Django 4.0.3 on 2022-10-08 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_order_cupon_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='zipcode',
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='customer',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.RemoveField(
            model_name='shippingaddress',
            name='order',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='order',
            field=models.ManyToManyField(to='store.order'),
        ),
    ]
