# Generated by Django 4.0.3 on 2022-10-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_latestarrivals_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='latestarrivals',
            name='products_for',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
