# Generated by Django 4.0.2 on 2022-10-21 16:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_latestarrivals_products_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='latestarrivals',
            name='products',
            field=models.ManyToManyField(to='store.Product'),
        ),
        migrations.AlterField(
            model_name='shippingaddress',
            name='order',
            field=models.ManyToManyField(to='store.Order'),
        ),
        migrations.CreateModel(
            name='ReviewImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, default='product-pic.jpg', null=True, upload_to='')),
                ('review', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.review')),
            ],
        ),
    ]
