# Generated by Django 4.0.2 on 2022-10-22 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0020_homebannercategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_heading', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(blank=True, default='product-pic.jpg', null=True, upload_to='')),
                ('estimated_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='store.category')),
            ],
        ),
    ]
