# Generated by Django 4.0.2 on 2022-10-22 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0021_collectioncategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopNowCategorys',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('sub_title', models.CharField(blank=True, max_length=200, null=True)),
                ('category_for', models.CharField(blank=True, max_length=200, null=True)),
                ('img', models.ImageField(blank=True, default='product-pic.jpg', null=True, upload_to='')),
            ],
        ),
    ]
