# Generated by Django 4.0.2 on 2022-10-22 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0022_shopnowcategorys'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopnowcategorys',
            name='estimated_category',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='store.category'),
        ),
    ]
