# Generated by Django 4.0.2 on 2022-10-22 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_shopnowcategorys_estimated_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('place', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('img', models.ImageField(blank=True, default='product-pic.jpg', null=True, upload_to='')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
