# Generated by Django 4.0.2 on 2022-10-25 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_remove_shippingaddress_order_order_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Customer Confirmed', 'Customer Confirmed'), ('Admin Confirmed', 'Admin Confirmed'), ('In-Transit', 'In-Transit'), ('Delivered', 'Delivered')], default='Pending', max_length=200, null=True),
        ),
    ]
