# Generated by Django 4.0.2 on 2022-10-25 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_order_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='member_amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
    ]
